import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "../components/theme-provider";
import { cn } from "@/src/lib/utils";
import { inter } from "./font";
import { Navbar } from "../components/Navbar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Trading Platform",
  description: "A modern trading platform",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body 
        className={cn(
          "min-h-screen bg-background font-sans text-foreground antialiased",
          inter.variable, 
        )}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Navbar/>
          {children}
          <Toaster/>
       </ThemeProvider>
      </body>
    </html>
  );
}

/* import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Appbar } from "./components/Appbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Appbar/>
        {children}
      </body>
    </html>
  );
}
 */